site_name: Grupales de BD Grupo C 22/23
site_url: https://www.grupalesbdc.ga/
theme:
  name: 'material'
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - navigation.top
  icon:
    logo: material/database
    repo: simple/git
  favicon: img/favicon.ico
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Cambiar a tema oscuro
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Cambiar a tema normal
nav:
    - Home: index.md
    - Práctica 1 servidores y clientes:
        - 'Introducción': 'p1-servidores-clientes/intro.md'
        - Responsabilidad individual:
            - 'Alumno 1: Adrián': 'p1-servidores-clientes/ri/alumno1.md'
            - 'Alumno 2: José Juan': 'p1-servidores-clientes/ri/alumno2.md'
            - 'Alumno 3: Arantxa': 'p1-servidores-clientes/ri/alumno3.md'
            - 'Alumno 4: Antonio': 'p1-servidores-clientes/ri/alumno4.md'
        - Responsabilidad grupal:
            - 'SQL Developer': 'p1-servidores-clientes/rg/sql-developer.md'
            - 'phpPgAdmin': 'p1-servidores-clientes/rg/herramienta-postgresql.md'
            - 'phpMyAdmin': 'p1-servidores-clientes/rg/phpmyadmin.md'
            - 'MongoDB-PHP-GUI': 'p1-servidores-clientes/rg/herramienta-mongodb.md'
            - 'Oracle Enterprise Manager': 'p1-servidores-clientes/rg/oracle-enterprise-manager.md'
    - Práctica 4 grupal de PL/SQL:
        - 'Introducción': 'p4-grupal-plsql/intro.md'
        - 'Pasos previos': 'p4-grupal-plsql/pasos-previos.md'
        - 'Ejercicio 1': 'p4-grupal-plsql/ejercicio1.md'
        - 'Ejercicio 2': 'p4-grupal-plsql/ejercicio2.md'
        - 'Ejercicio 3': 'p4-grupal-plsql/ejercicio3.md'
        - 'Ejercicio 3 PostgreSQL': 'p4-grupal-plsql/ejercicio3-postgres.md'
        - 'Ejercicio 4': 'p4-grupal-plsql/ejercicio4.md'
        - 'Ejercicio 5': 'p4-grupal-plsql/ejercicio5.md'
        - 'Ejercicio 5 PostgreSQL': 'p4-grupal-plsql/ejercicio5-postgres.md'
        - 'Ejercicio 6': 'p4-grupal-plsql/ejercicio6.md'
        - 'Ejercicio 7': 'p4-grupal-plsql/ejercicio7.md'
        - 'Ejercicio 8': 'p4-grupal-plsql/ejercicio8.md'
    - Práctica 5 usuarios:
        - 'Introducción': 'p5-usuarios/intro.md'
        - Responsabilidad individual:
            - 'Alumno 1: Adrián': 'p5-usuarios/ri/alumno1.md'
            - 'Alumno 2: José Juan': 'p5-usuarios/ri/alumno2.md'
            - 'Alumno 3: Arantxa': 'p5-usuarios/ri/alumno3.md'
            - 'Alumno 4: Antonio': 'p5-usuarios/ri/alumno4.md'
        - Responsabilidad grupal:
            - Caso práctico 1:
                - 'Ejercicio 1': 'p5-usuarios/rg/caso-practico-1-ej1.md'
                - 'Ejercicio 2': 'p5-usuarios/rg/caso-practico-1-ej2.md'
                - 'Ejercicio 3': 'p5-usuarios/rg/caso-practico-1-ej3.md'
                - 'Ejercicio 4 Oracle': 'p5-usuarios/rg/caso-practico-1-ej4-oracle.md'
                - 'Ejercicio 4 PostgreSQL': 'p5-usuarios/rg/caso-practico-1-ej4-postgres.md'
                - 'Ejercicio 5': 'p5-usuarios/rg/caso-practico-1-ej5.md'
            - 'Caso práctico 2':
                - 'Ejercicio 1': 'p5-usuarios/rg/caso-practico-2-ej1.md'
                - 'Ejercicio 2': 'p5-usuarios/rg/caso-practico-2-ej2.md'
                - 'Ejercicio 3': 'p5-usuarios/rg/caso-practico-2-ej3.md'
                - 'Ejercicio 4': 'p5-usuarios/rg/caso-practico-2-ej4.md'
            - 'Ejercicio grupal 3': 'p5-usuarios/rg/ejercicio-grupal-3.md'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
extra_css:
  - stylesheets/asciinema-player.css
extra_javascript:
  - javascripts/asciinema-player.min.js
plugins:
  - glightbox
  - search
  - mkdocs-asciinema
repo_url: https://github.com/adriasir123/grupalesbdc
repo_name: Repositorio
